language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"

cache:
  directories:
    - node_modules

before_install:
  - if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi

script: npm run ci
conditions:
  branch:master: npm test 
  default: npm test
